//! Dependent optics before the coend quotient (Definition 1).
//!
//! A witness `⟨l | r⟩` keeps its representative 1-cell. Identity is equation (2)
//! and composition is equation (3). The generating equivalence under Definition 1
//! is [`related_by`]: a 2-cell `m: f ⇒ g` identifies `(L(m) ∘ l, r)` with
//! `(l, r ∘ R(m))`.

use crate::slice::{self, SliceMor, SliceObj};
use crate::span::{self, Span, TwoCell};

/// An object `(X, X')_A` of `Optic`, with both fibres slices (dependent lenses).
#[derive(Clone, PartialEq, Eq, Debug)]
pub struct Family {
    pub forward: SliceObj,
    pub backward: SliceObj,
}

impl Family {
    pub fn check(&self) {
        self.forward.check();
        self.backward.check();
        assert_eq!(self.forward.base, self.backward.base);
    }
}

/// A representative-explicit optic between two families.
#[derive(Clone, PartialEq, Eq, Debug)]
pub struct Witness {
    pub dom: Family,
    pub cod: Family,
    pub span: Span,
    /// `X → f* Y` over `A`.
    pub fwd: SliceMor,
    /// `f* Y' → X'` over `A`.
    pub bwd: SliceMor,
}

impl Witness {
    pub fn check(&self) {
        self.dom.check();
        self.cod.check();
        self.span.check();
        assert_eq!(self.span.left, self.dom.forward.base);
        assert_eq!(self.span.right, self.cod.forward.base);
        self.fwd.check();
        self.bwd.check();
        assert_eq!(self.fwd.dom, self.dom.forward);
        assert_eq!(self.bwd.cod, self.dom.backward);
        let expected_fwd_cod = slice::reindex_obj(&self.span, &self.cod.forward);
        let expected_bwd_dom = slice::reindex_obj(&self.span, &self.cod.backward);
        assert_eq!(self.fwd.cod, expected_fwd_cod, "forward leg lands in f* Y");
        assert_eq!(
            self.bwd.dom, expected_bwd_dom,
            "backward leg starts at f* Y'"
        );
    }
}

/// Equation (2): `⟨θ_A(X) | θ_A^{-1}(X')⟩` on the identity span.
pub fn identity(dom: &Family) -> Witness {
    let span = span::identity(dom.forward.base);
    Witness {
        dom: dom.clone(),
        cod: dom.clone(),
        span,
        fwd: slice::theta_id(&dom.forward),
        bwd: slice::theta_id_inv(&dom.backward),
    }
}

/// Equation (3). `outer ∘ inner` applies `inner` first.
pub fn compose(outer: &Witness, inner: &Witness) -> Witness {
    assert_eq!(
        inner.cod, outer.dom,
        "optic composition: intermediate object"
    );
    let f = &inner.span;
    let g = &outer.span;
    let f_l2 = slice::reindex_mor(f, &outer.fwd);
    let theta = slice::theta_comp(f, g, &outer.cod.forward);
    let fwd = slice::compose(&theta, &slice::compose(&f_l2, &inner.fwd));

    let theta_inv = slice::theta_comp_inv(f, g, &outer.cod.backward);
    let f_r2 = slice::reindex_mor(f, &outer.bwd);
    let bwd = slice::compose(&inner.bwd, &slice::compose(&f_r2, &theta_inv));
    Witness {
        dom: inner.dom.clone(),
        cod: outer.cod.clone(),
        span: span::compose(g, f),
        fwd,
        bwd,
    }
}

/// The one-step relation generated by a 2-cell `m: inner_span ⇒ outer_span`.
pub fn related_by(m: &TwoCell, left: &Witness, right: &Witness) -> bool {
    if left.dom != right.dom || left.cod != right.cod {
        return false;
    }
    if !span::cell_commutes(m, &left.span, &right.span) {
        return false;
    }
    let lm = slice::act_two_cell(m, &left.span, &right.span, &left.cod.forward);
    let rm = slice::act_two_cell(m, &left.span, &right.span, &left.cod.backward);
    slice::compose(&lm, &left.fwd) == right.fwd && left.bwd == slice::compose(&right.bwd, &rm)
}

/// Some 2-cell exhibits the generating equivalence in either direction.
pub fn equivalent(a: &Witness, b: &Witness) -> bool {
    if a.dom != b.dom || a.cod != b.cod {
        return false;
    }
    span::two_cells(&a.span, &b.span)
        .iter()
        .any(|m| related_by(m, a, b))
        || span::two_cells(&b.span, &a.span)
            .iter()
            .any(|m| related_by(m, b, a))
}
